name: CI/CD - frontend-app

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        # npm ci will install exactly what's in package-lock.json
        run: npm ci

      - name: Audit Dependencies (optional)
        # fails if vulnerabilities ≥ high
        run: npm audit --audit-level=high

      - name: Build for Production
        run: ng build --configuration=production